### ISSUE TITLE
SSL certificates path

### ISSUE THREAD

**Issue by lucasvr** [gobolinux/GoboALFS#9]
We currently have certs installed on /System/Index/lib/ssl/certs, whereas some packages look for certs under /System/Settings/ssl/certs. All the major distros out there are using /System/Settings/ssl/certs, so we should ensure that we're using the same path as well for the sake of binary compatibility and maintenance.

**Comment by AitorATuin** [comment]
@lucasvr can this be closed?

**Comment by lucasvr** [comment]
That looks good to me. Thanks, Aitor, I'm closing this issue now.

**Comment by hishamhm** [comment]
Is OpenSSL from a new ISO build coming from ALFS or from the recipe?

**Comment by AitorATuin** [comment]
good question, I was assuming that from the recipe since the previous one was broken.

**Comment by lucasvr** [comment]
I just checked and it's coming from ALFS

**Comment by AitorATuin** [comment]
AFAIR from  a previous conversation on IRC @lucasvr told me that at some point we were updating it with the version coming from the Recipe which makes sense since the [lfs](http://www.linuxfromscratch.org/blfs/view/svn/postlfs/openssl.html) version uses `/etc/ssl` when configuring it and our old recipe was using `lib`. That would explain why our paths were messed up.
